# =================================
# = Server
# =================================
server:
  port: 8080
  servlet:
    context-path: /v1/miniautorizador

# =================================
# = Spring
# =================================
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/miniautorizador?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    properties:
      hibernate:
        show_sql: true